### ISSUE TITLE
can you share a requirements.txt of this project?

### ISSUE THREAD

**Issue by wuyongyi** [timoklein/alphazero-gym#1]
I can not install this project in my osx 11.2.3 from latest vesion of conda. Maybe a requirements.txt is better.

**Comment by timoklein** [comment]
I'll have to create a minimal one from scratch. It might take a couple of days since I have a deadline on Thursday but it's in my todos.

**Comment by timoklein** [comment]
@wuyongyi I've uploaded a minimal requirements.txt. Can you test if it works for you?

**Comment by wuyongyi** [comment]
It works for me(python 3.7.11, torch 1.9, osx 11.2.3). Thanks! 
by the way, the line 143,162 in two run_*.py should be 
#########
pbar.set_description(f'ep = {ep}, reward = {reward} , t_total={t_total} ')
#########
