### ISSUE TITLE
Config Error 

### ISSUE THREAD

**Issue by AlexLup** [timoklein/alphazero-gym#13]
I was trying to run 'run_continuous.py' to test the code but I got some errors with the config files.

MCTSContinous.yaml misses a field "model"
RMSProp.yaml misses a field "params"

Both are required arguments and I can not figure out how to solve the problem.

**Comment by timoklein** [comment]
Hi Alex, what version of hydra are you using? I think sticking exactly to `hydra-core==1.0.6` should fix your problem. Any higher version had some breaking changes.

**Comment by AlexLup** [comment]
That was exactly the problem, I had the last version of hydra-core my bad. Thank you
